@echo off
REM ───────────────────────────────────────────────────────────────────────────
REM e-con DepthVista Helix iToF — Isaac Sim installer (Windows)
REM
REM ZED-style install: clone the e-con GitHub repo (USDs + the pure-Python
REM `econ.itof.menu` extension) and register it with Isaac Sim, so the camera
REM shows up under Create -> Sensors -> Camera and Depth Sensors -> e-con.
REM
REM Unlike ZED's build.bat there is NOTHING to compile — the extension is pure
REM Python, so this script only clones and registers. Registration is done by
REM generating a launcher that passes --ext-folder/--enable, because editing
REM Isaac Sim 5.1's persistent config is unreliable (IsaacSim issues #376/#377).
REM
REM Usage:
REM   build.bat                 - clone (if needed) + register
REM   build.bat <repo-url>      - override REPO_URL
REM   set REPO_URL=... & set INSTALL_DIR=... & set ISAACSIM_PATH=... & build.bat
REM ───────────────────────────────────────────────────────────────────────────
setlocal enabledelayedexpansion
set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

REM ── Configuration (override via env or 1st arg) ──────────────────────────────
if not defined REPO_URL set "REPO_URL=%~1"
if not defined REPO_URL set "REPO_URL=https://github.com/Thagasheriff64/econ-isaac-sim.git"
if not defined EXT_NAME set "EXT_NAME=econ.itof.menu"

REM If run from inside a clone (exts\<EXT_NAME> beside the script), install in place.
if not defined INSTALL_DIR (
    if exist "%SCRIPT_DIR%\exts\%EXT_NAME%" (
        set "INSTALL_DIR=%SCRIPT_DIR%"
    ) else (
        set "INSTALL_DIR=%USERPROFILE%\econ-isaac-sim"
    )
)

REM ── 1. Clone or update the repo ──────────────────────────────────────────────
where git >nul 2>&1
if errorlevel 1 (
    echo [ERROR] git is not installed. Install git and re-run.
    exit /b 1
)

if exist "%INSTALL_DIR%\.git" (
    echo [INFO] Updating existing clone at %INSTALL_DIR% ...
    git -C "%INSTALL_DIR%" pull --ff-only
) else if exist "%INSTALL_DIR%\exts\%EXT_NAME%" (
    echo [INFO] Running from inside the repo at %INSTALL_DIR% - skipping clone.
) else (
    echo [INFO] Cloning %REPO_URL% -^> %INSTALL_DIR% ...
    git clone "%REPO_URL%" "%INSTALL_DIR%"
    if errorlevel 1 (
        echo [ERROR] git clone failed.
        exit /b 1
    )
)

REM ── 2. Sanity-check the extension is present (do NOT build anything) ─────────
set "EXT_DIR=%INSTALL_DIR%\exts\%EXT_NAME%"
if not exist "%EXT_DIR%" (
    echo [ERROR] Extension not found at %EXT_DIR%.
    echo [ERROR] The cloned repo must contain exts\%EXT_NAME%\ ^(config\extension.toml + python^).
    exit /b 1
)
echo [INFO] Found extension: %EXT_DIR%

REM ── 3. Locate the Isaac Sim install (holds isaac-sim.bat) ────────────────────
if not defined ISAACSIM_PATH if defined ISAAC_SIM_PATH set "ISAACSIM_PATH=%ISAAC_SIM_PATH%"
if not defined ISAACSIM_PATH (
    for %%D in (
        "%LOCALAPPDATA%\ov\pkg\isaac-sim-*"
        "%LOCALAPPDATA%\ov\pkg\isaac_sim-*"
        "%USERPROFILE%\isaacsim"
        "%USERPROFILE%\isaac-sim"
        "%USERPROFILE%\Downloads\isaacsim"
        "%USERPROFILE%\Downloads\isaac-sim*"
        "%USERPROFILE%\ROBOTICS\downloads\isaacsim"
        "C:\isaacsim"
        "C:\isaac-sim"
    ) do (
        for /d %%P in (%%~D) do (
            if exist "%%~P\isaac-sim.bat" set "ISAACSIM_PATH=%%~P"
        )
        if not defined ISAACSIM_PATH if exist "%%~D\isaac-sim.bat" set "ISAACSIM_PATH=%%~D"
    )
)

if not defined ISAACSIM_PATH goto :no_isaac
if not exist "%ISAACSIM_PATH%\isaac-sim.bat" goto :no_isaac
echo [INFO] Using Isaac Sim at: %ISAACSIM_PATH%

REM ── 4. Generate the launcher (the reliable registration mechanism) ───────────
set "LAUNCHER=%INSTALL_DIR%\start-isaacsim-econ.bat"
(
    echo @echo off
    echo REM Auto-generated by build.bat — launches Isaac Sim with the e-con camera extension.
    echo REM Re-run build.bat to regenerate after moving the install or Isaac Sim.
    echo "%ISAACSIM_PATH%\isaac-sim.bat" --ext-folder "%INSTALL_DIR%\exts" --enable "%EXT_NAME%" %%*
) > "%LAUNCHER%"
echo [INFO] Wrote launcher: %LAUNCHER%

REM ── 5. Best-effort persistent registration (non-fatal; launcher is the real one)
set "PYEXE="
where py  >nul 2>&1 && set "PYEXE=py"
if not defined PYEXE ( where python >nul 2>&1 && set "PYEXE=python" )
if defined PYEXE (
    set "REGPY=%TEMP%\econ_isaac_register.py"
    >  "!REGPY!" echo import glob, json, os, sys
    >> "!REGPY!" echo ext_folder = sys.argv[1]
    >> "!REGPY!" echo pattern = os.path.join(os.environ.get("LOCALAPPDATA",""), "ov","data","Kit","Isaac-Sim*","*","user.config.json")
    >> "!REGPY!" echo cfgs = glob.glob(pattern)
    >> "!REGPY!" echo for cfg in cfgs:
    >> "!REGPY!" echo ^    try:
    >> "!REGPY!" echo ^        data = json.load(open(cfg))
    >> "!REGPY!" echo ^    except Exception:
    >> "!REGPY!" echo ^        continue
    >> "!REGPY!" echo ^    folders = data.setdefault("exts", {}).setdefault("folders", [])
    >> "!REGPY!" echo ^    if isinstance(folders, list) and ext_folder not in folders:
    >> "!REGPY!" echo ^        folders.append(ext_folder)
    >> "!REGPY!" echo ^        json.dump(data, open(cfg, "w"), indent=2)
    >> "!REGPY!" echo ^        print("[INFO] Added ext-folder to", cfg, "(best-effort; may reset on 5.1).")
    "!PYEXE!" "!REGPY!" "%INSTALL_DIR%\exts" || echo [INFO] Persistent-config update skipped ^(non-fatal^).
    del /q "!REGPY!" >nul 2>&1
)

REM ── 6. Done ──────────────────────────────────────────────────────────────────
echo.
echo [SUCCESS] e-con DepthVista Helix installed.
echo.
echo   Launch Isaac Sim with:
echo       %LAUNCHER%
echo.
echo   Then in the viewport menu:
echo       Create -^> Sensors -^> Camera and Depth Sensors -^> e-con
echo           - DepthVista Helix iToF ^(USB^)
echo           - DepthVista Helix iToF ^(GMSL^)
exit /b 0

:no_isaac
echo [ERROR] Could not find isaac-sim.bat. Set ISAACSIM_PATH=C:\path\to\isaacsim and re-run.
echo.
echo [FALLBACK] Register manually instead:
echo   1. Launch Isaac Sim.
echo   2. Window -^> Extensions -^> (gear) -^> add this path to the search paths:
echo          %INSTALL_DIR%\exts
echo   3. In the Third-Party tab, enable: %EXT_NAME%
echo   Then: Create -^> Sensors -^> Camera and Depth Sensors -^> e-con
exit /b 1
